Moved config and state files to standard locations, added instructions to README.

diff --git a/irtvboxlaunch b/irtvboxlaunch
--- a/irtvboxlaunch
+++ b/irtvboxlaunch
@@ -5,13 +5,20 @@
 # runs tvbox
 
 # prevent multiple instances
-if [ `pgrep -c irtvboxlaunch` -gt 1 ]; then
-	echo duplicate instance, abort
+if [ $(pgrep -c irtvboxlaunch) -gt 1 ]; then
+	echo "duplicate instance, abort"
 	exit
 fi
 
-# shellcheck source=tvbox.conf.example
-source ~/.tvbox.conf
+if [ -r "$XDG_CONFIG_HOME/tvboxrc" ]; then
+  source "$XDG_CONFIG_HOME/tvboxrc"
+elif [ -r ~/.config/tvboxrc ]; then
+  # shellcheck source=tvboxrc.example
+  source ~/.config/tvboxrc
+else
+  echo "Could not load tvboxrc, abort" >&2
+  exit 1
+fi
 
 pkill -f 'python.*tvbox.*'
 pkill -f 'feh.*tvbox.*'
@@ -25,4 +32,4 @@ pkill -f -9 'lxterminal.*tvbox.*'
 killall -9 tvbox
 killall -9 tvboxlaunchchain2
 
-$TVBOX_DIR/tvbox #--no-delay
+"$TVBOX_DIR/tvbox" #--no-delay
diff --git a/tvbox b/tvbox
--- a/tvbox
+++ b/tvbox
@@ -4,30 +4,38 @@
 # can be run directly or by irtvboxlaunch
 # runs tvboxlaunchchain2.sh
 
-# shellcheck source=tvbox.conf.example
-source ~/.tvbox.conf
+if [ -r "$XDG_CONFIG_HOME/tvboxrc" ]; then
+  source "$XDG_CONFIG_HOME/tvboxrc"
+elif [ -r ~/.config/tvboxrc ]; then
+  # shellcheck source=tvboxrc.example
+  source ~/.config/tvboxrc
+else
+  echo "Could not load tvboxrc, abort" >&2
+  exit 1
+fi
 
 # make sure it's not already running
 if pgrep -fa 'feh.*tvbox.*'; then
-	echo "feh already running, abort" >&2
+	echo "feh tvbox already running, abort" >&2
 	exit 1
 fi
 if pgrep -fa 'python.*tvbox.*'; then
-	echo "python3 already running, abort" >&2
+	echo "python3 tvbox already running, abort" >&2
 	exit 1
 fi
 
 # splash screen
 if [ "$1" != "--no-delay" ]; then
 	feh -F "$TVBOX_DIR/images/tvbox-splash.png" &
-	# this is to give it a chance to sync the time via NTP. ideally it should have an RTC.
-	sleep $TVBOX_SPLASH_DELAY
+	# this is to give the raspi a chance to sync the time via NTP. ideally it should have an RTC.
+	#TODO: make this check for NTP time sync to avoid having to wait the full timeout every time
+	sleep "$TVBOX_SPLASH_TIMEOUT"
 	pkill -f 'feh.*tvbox.*'
 fi
 
 # are we already in a terminal window?
 if [ "$TERM" == "xterm-256color" ]; then
-	bash $TVBOX_DIR/tvboxlaunchchain2.sh
+	bash "$TVBOX_DIR/tvboxlaunchchain2.sh"
 else
 	lxterminal -t tvboxterm -e "bash $TVBOX_DIR/tvboxlaunchchain2.sh"
 fi
