tweaked splash screen stuff

diff --git a/tvbox b/tvbox
--- a/tvbox
+++ b/tvbox
@@ -5,13 +5,13 @@
 # runs tvboxlaunchchain2.sh
 
 if [ -r "$XDG_CONFIG_HOME/tvboxrc" ]; then
-  source "$XDG_CONFIG_HOME/tvboxrc"
+	source "$XDG_CONFIG_HOME/tvboxrc"
 elif [ -r ~/.config/tvboxrc ]; then
-  # shellcheck source=tvboxrc.example
-  source ~/.config/tvboxrc
+	# shellcheck source=tvboxrc.example
+	source ~/.config/tvboxrc
 else
-  echo "Could not load tvboxrc, abort" >&2
-  exit 1
+	echo "Could not load tvboxrc, abort" >&2
+	exit 1
 fi
 
 # make sure it's not already running
@@ -25,23 +25,21 @@ if pgrep -fa 'python.*tvbox.*'; then
 fi
 
 # splash screen
+# this is mostly to allow Raspberry Pi to sync time via NTP on startup. Ideally it would have an RTC instead.
 if [ "$1" != "--no-delay" ]; then
 	feh -F "$TVBOX_DIR/images/tvbox-splash.png" &
-	# this is to give the raspi a chance to sync the time via NTP. ideally it should have an RTC.
 
-  sleep 2
+	sleep "$TVBOX_SPLASH_MIN"
 
-	for (( i=1; i<=TVBOX_SPLASH_TIMEOUT; i++ )); do
-    if timedatectl show --property=NTPSynchronized | grep yes; then
-      break
-    fi
-    sleep 1
-  done
+	for (( i=1; i<=TVBOX_SPLASH_MAX; i++ )); do
+		if timedatectl show --property=NTPSynchronized | grep yes; then
+			break
+		fi
+		sleep 1
+	done
 
 	pkill -f 'feh.*tvbox.*'
 fi
-
-exit
 
 # are we already in a terminal window?
 if [ "$TERM" == "xterm-256color" ]; then
